# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]
jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [17]
        # and run on both Linux and Windows
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.is-release }}
          cache-read-only: false

      - name: build (Linux)
        if: ${{ runner.os != 'Windows' }}
        run: ./gradlew build
        
      - name: build (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: .\gradlew.bat build

      - name: Accept EULA
        if: ${{ !inputs.is-release }}
        run: |
          mkdir -p run
          echo "eula=true" > run/eula.txt
          
      - name: Run Gametests (Linux)
        if: ${{ !inputs.is-release && runner.os != 'Windows' }}
        shell: bash
        run: .\gradlew runGameTestServer
    

      - name: Publish
        if: ${{ inputs.is-release }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishMods
