# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      is-release:
        description: 'Publish release to Modrinth, Curseforge and Github'
        required: false
        default: false
        type: boolean
jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [17]
        # and run on both Linux and Windows
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ startsWith(github.ref, 'refs/tags/') }}
          cache-read-only: false

      - name: build (Linux)
        run: ./gradlew build

      - name: Accept EULA
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -p run
          echo "eula=true" > run/eula.txt
      

      #      - name: Run Test Client
      #        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #        run: |
      #          ./gradlew runClient --stacktrace &
      #          PID=$!
      #          sleep 30
      #          kill $PID || true
      #        timeout-minutes: 2

      - name: Run Test Server
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./gradlew runServer --stacktrace &
          PID=$!
          sleep 30
          kill $PID || true
        timeout-minutes: 2

      - name: Publish to GitHub Packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --stacktrace